name: Build & Push Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if server changed
        id: server-changes
        uses: tj-actions/changed-files@v44
        with:
          files: server/**

      - name: Log in to GitHub Container Registry
        if: steps.server-changes.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        if: steps.server-changes.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if client changed
        id: client-changes
        uses: tj-actions/changed-files@v44
        with:
          files: client/**

      - name: Log in to GitHub Container Registry
        if: steps.client-changes.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        if: steps.client-changes.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
